apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
  labels:
    type: grafana
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-XXXXXXXXXXXXXXXXX
  capacity:
    storage: 10Gi