restartPolicy: Always
kind: Deployment

pspEnabled: true
hostNetwork: false

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate

image:
  repository: prometheus/blackbox-exporter
  pullPolicy: IfNotPresent

nodeSelector:
  eks.amazonaws.com/nodegroup: monitoring
  kubernetes.io/arch: arm64

tolerations:
  - key: system-type
    operator: Equal
    value: monitoring
    effect: NoSchedule
  - key: arch-type
    operator: Equal
    value: arm
    effect: NoSchedule

affinity: {}

config:
  modules:
    http_2xx:
      prober: http
      timeout: 1s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: false
        preferred_ip_protocol: "ip4"

ingress:
  enabled: false
  
replicas: 1

serviceMonitor:
  enabled: true

  defaults:
    additionalMetricsRelabels: {}
    additionalRelabeling: []
    labels: {}
    interval: 30s
    scrapeTimeout: 30s
    module: http_2xx
  scheme: http

prometheusRule:
  enabled: false
  additionalLabels: {}
  namespace: ""
  rules: []

networkPolicy:
  enabled: false
