config:
  enabled: true
  logLevel: info
  logFormat: logfmt
  serverPort: 3101
  clients:
    - url: http://loki-gateway/loki/api/v1/push
      tenant_id: 1

priorityClassName: system-cluster-critical

tolerations:
  - operator: Exists
#  - key: node-role.kubernetes.io/master
#    operator: Exists
#    effect: NoSchedule
#  - key: node-role.kubernetes.io/control-plane
#    operator: Exists
#    effect: NoSchedule